<?php
/*
  $Id$

  generated by: 
  https://oscompose.com (c)2018

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Copyright (c) 2018 osCommerce

  Released under the GNU General Public License
  Copyright Z.Iqbal GDPR Cookie Widgets V1.2 18-11-2018
  
 

*/

  define('MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_TITLE', 'JcM cookieconsent1');
  define('MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_DESCRIPTION', 'JcM cookieconsent1');

