<?php
/*
  $Id$

  generated by: 
  https://oscompose.com (c)2018

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Copyright (c) 2018 osCommerce

  Released under the GNU General Public License
  Copyright Z.Iqbal GDPR Cookie Widgets V1.2 18-11-2018
  
  

*/

  class ht_jcm_cookieconsent1 {
    var $code = 'ht_jcm_cookieconsent1';
    var $group = 'footer_scripts';  //'header_tags'
    var $title;
    var $description;
    var $sort_order;
    var $enabled = false;
    
    

    function __construct() {
      $this->title = MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_TITLE;
      $this->description = MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_DESCRIPTION;

      if ( defined('MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_STATUS') ) {
        $this->sort_order = MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_SORT_ORDER;
        $this->enabled = (MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_STATUS == 'True');
        
      }
    }

    function execute() {
      global $oscTemplate;


    
    $oscTemplate->addBlock( '<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />' . "\n", $this->group);
	$oscTemplate->addBlock( '<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>' . "\n", $this->group);
    $oscTemplate->addBlock( '<script> 
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "' . MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_BACKC . '",
      "text":  "' . MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_TEXTC . '"
    },
    "button": {
      "background": "' . MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_BUTBACKC . '",
      "text": "' . MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_BUTTC . '"
    }
  },
  "theme": "edgeless",
  "position": "' . MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_POS . '",
  "type": "' . MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_OPT . '",
  "content": {
    "message": "' . MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_MESS . '" ,
    "dismiss": "' . MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_DISM . '" ,
    "deny": "' . MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_DENY .'" ,
    "link": "' . MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_LINKT . '" ,
    "href": "' . MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_LINKURL . '",
  }
})});
</script>' . "\n", $this->group);
	
    
	
	

          }

    function isEnabled() {
      return $this->enabled;
    }

    function check() {
      return defined('MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_STATUS');
    }

    function install() {
      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Enable JcM cookieconsent Module', 'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_STATUS', 'True', 'Do you want to allow JcM cookieconsent footer script to be added to the page footer?', '6', '1', 'tep_cfg_select_option(array(\'True\', \'False\'), ', now())");
      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('JcM cookieconsent', 'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_DESCRIPTION_STATUS', 'True', 'JcM cookieconsent', '6', '0', 'tep_cfg_select_option(array(\'True\'), ', now())");
      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Sort Order', 'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_SORT_ORDER', '0', 'Sort order of display. Lowest is displayed first.', '6', '0', now())");
      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('background color', 'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_BACKC', '#eaf7f7', 'Set background color', '6', '8', now())");
      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('text color', 'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_TEXTC', '#5c7291', 'Set text color', '6', '8', now())");
      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('button background color', 'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_BUTBACKC', '#56cbdb', 'Set button background color', '6', '8', now())");
      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('button text color', 'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_BUTTC', '#ffffff', 'Set button text color', '6', '8', now())");
      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('position top/bottom or bottom-left/bottom-right', 'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_POS', 'top', 'Set position top or bottom', '6', '8', now())");
      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('cookie Select opt-in or opt-out', 'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_OPT', 'opt-in', 'Select opt-in or opt-out', '6', '8', now())");
      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('cookie message', 'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_MESS', 'Este sitio web utiliza cookies para garantizar que tenga la mejor experiencia en nuestro sitio web', 'Set cookie message', '6', '8', now())");
      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('dismiss message', 'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_DISM', '¡Entiendo!', 'Set dismiss message', '6', '8', now())");
      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('deny message', 'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_DENY', 'Rechazar cookies', 'Set deny message', '6', '8', now())");
      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('link text', 'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_LINKT', 'Aprende más', 'Set link text', '6', '8', now())");
      tep_db_query("insert into configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('link url', 'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_LINKURL', 'https://www.tbyb.co.uk/privacy.php', 'Set link url', '6', '8', now())");
  
    }

    function remove() {
      tep_db_query("delete from configuration where configuration_key in ('" . implode("', '", $this->keys()) . "')");
    }

    function keys() {
      return array('MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_STATUS',
      'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_SORT_ORDER',
      'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_BACKC',
      'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_TEXTC',
      'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_BUTBACKC',
      'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_BUTTC',
      'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_POS',
      'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_OPT',
      'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_MESS',
      'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_DISM',
      'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_DENY',
      'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_LINKT',
      'MODULE_HEADER_TAGS_JCM_COOKIECONSENT1_LINKURL');
    }
  }
